const TOKENS_TO_MONITOR: any = []
const ETH_AMOUNT_TO_BUY = 0.0001 * 10 * 18
const BNB_AMOUNT_TO_BUY = 0.001 * 10 ** 18


const ADDITIONAL_BUY_GAS = 1 * 10 ** 9
const ADDITIONAL_GAS_SELL = 1 * 10 ** 9
const AUTHORISED_USERS: any = []

export { TOKENS_TO_MONITOR, AUTHORISED_USERS, BNB_AMOUNT_TO_BUY, ADDITIONAL_BUY_GAS, ETH_AMOUNT_TO_BUY, ADDITIONAL_GAS_SELL }